# Generated by Django 3.2 on 2021-06-14 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('value', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('publication_date', models.DateField(default=django.utils.timezone.now)),
                ('closing_date', models.DateField(default=django.utils.timezone.now)),
                ('life_time_value', models.IntegerField(default=60)),
                ('is_active', models.BooleanField(default=False)),
                ('complete_code', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Код завершенного интервью')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('help_desc', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(choices=[('multiple', 'Возможно несколько ответов'), ('single', 'Один ответ')], default='single', max_length=200)),
                ('answer_option', models.ManyToManyField(to='survey.AnswerOption')),
            ],
        ),
        migrations.CreateModel(
            name='RespondentsAnswerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UsersAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.PositiveSmallIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.project')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.project', verbose_name='Проект')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question', verbose_name='Вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='RespondentsSurveyStatusData',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Complete', 'Завершенное интервью'), ('Incomplete', 'Незавершенное интервью'), ('Not started', 'Не начато')], default='Not started', max_length=100)),
                ('last_question', models.SmallIntegerField()),
                ('answers', models.ManyToManyField(through='survey.RespondentsAnswerData', to='survey.UsersAnswers')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.project', verbose_name='Проект')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='RespondentsAnswerData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.respondentssurveystatusdata')),
                ('user_answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.usersanswers')),
            ],
        ),
        migrations.AddField(
            model_name='respondentsanswerdata',
            name='survey_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.respondentssurveystatusdata'),
        ),
        migrations.AddField(
            model_name='respondentsanswerdata',
            name='user_answers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.usersanswers'),
        ),
        migrations.AddField(
            model_name='project',
            name='question',
            field=models.ManyToManyField(through='survey.Survey', to='survey.Question'),
        ),
    ]
