# Generated by Django 3.2 on 2021-06-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('single', 'Один ответ'), ('multiple', 'Возможно несколько ответов')], default='single', max_length=200),
        ),
        migrations.AlterField(
            model_name='respondentssurveystatusdata',
            name='last_question',
            field=models.SmallIntegerField(default=0),
        ),
    ]
