# Generated by Django 3.2 on 2021-04-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210425_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('multiple', 'multiple'), ('single', 'single')], default='single', max_length=200),
        ),
    ]
