# Generated by Django 3.2 on 2021-06-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20210615_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('single', 'Один ответ'), ('multiple', 'Возможно несколько ответов')], default='single', max_length=200),
        ),
        migrations.AlterField(
            model_name='respondentssurveystatusdata',
            name='answers',
            field=models.ManyToManyField(blank=True, through='survey.RespondentsAnswerData', to='survey.UsersAnswers'),
        ),
        migrations.AlterField(
            model_name='respondentssurveystatusdata',
            name='status',
            field=models.CharField(choices=[('Not started', 'Не начато'), ('Complete', 'Завершенное интервью'), ('Incomplete', 'Незавершенное интервью')], default='Not started', max_length=100),
        ),
    ]
