# Generated by Django 3.2 on 2021-04-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('single', 'single'), ('multiple', 'multiple')], default='single', max_length=200),
        ),
    ]
