# Generated by Django 3.2 on 2021-06-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20210615_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondentssurveystatusdata',
            name='status',
            field=models.CharField(choices=[('Incomplete', 'Незавершенное интервью'), ('Not started', 'Не начато'), ('Complete', 'Завершенное интервью')], default='Not started', max_length=100),
        ),
    ]
