# Generated by Django 3.2 on 2021-04-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_alter_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespondentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Answer_Option',
            new_name='AnswerOption',
        ),
    ]
