# Generated by Django 3.2 on 2021-05-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20210503_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='is_admin',
            field=models.CharField(choices=[('employer', 'Сотрудник'), ('HR', 'HR-специалист')], default='employer', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('single', 'single'), ('multiple', 'multiple')], default='single', max_length=200),
        ),
    ]
