# Generated by Django 3.2 on 2021-05-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20210503_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='is_admin',
            field=models.CharField(choices=[('HR', 'HR-специалист'), ('employer', 'Сотрудник')], default='employer', max_length=100),
        ),
    ]
